name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v[0-9]+.[0-9]+.[0-9]+-rc*' # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5
      - 'v[0-9]+.[0-9]+.[0-9]+-classic' # Push events to matching v*, i.e. v1.0-classic, v20.15.10-classic

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version tag
        run: echo "VERSION=$(echo ${{github.ref_name}} | sed 's/^v//')" >> $GITHUB_ENV
      
      - name: Create build directory
        run: mkdir -p build/release
      
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          tag_name: ${{github.ref_name}}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            build/release/*
